### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by kwaite1021** [b1lly/gumi#37]
For giving us this - you are the only author I have seen for dropdowns that took the time to do this amount of documentation. The CSS iss simple and readable, and I loved that I can style the  button so easily with it. Awesome !! As a beginner I appreciate all the documentation I can get.
THANK YOU !

Can send this issue to /dev/null now

**Comment by b1lly** [comment]
Hi Kwaite, 

Thank you for the compliment ;). Have a good one!
